name: Deploy, copy to LuckyDogeShit.com

on:
  push:
    branches:
      - main
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: |
          rm ./.github -rf
          echo luckydogeshit.com > CNAME
          git config --local user.name "${{ secrets.GIT_ACTION_EMAIL }}"
          git config --local user.email "${{ secrets.GIT_ACTION_EMAIL }}"
          git commit -m "Copied from dogeshit.io" -a

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          repository: dogeshit/luckydogeshit.com
